"""
Django settings for ecommerce_project project.
Generated by 'django-admin startproject' using Django 6.0.3.
"""

import os
from pathlib import Path
from django.contrib.admin.apps import AdminConfig
from django.contrib.auth.apps import AuthConfig
from django.contrib.contenttypes.apps import ContentTypesConfig

# Custom Configs to handle MongoDB ObjectIDs for built-in Django apps
class MongoAdminConfig(AdminConfig):
    default_auto_field = 'django_mongodb_backend.fields.ObjectIdAutoField'

class MongoAuthConfig(AuthConfig):
    default_auto_field = 'django_mongodb_backend.fields.ObjectIdAutoField'

class MongoContentTypesConfig(ContentTypesConfig):
    default_auto_field = 'django_mongodb_backend.fields.ObjectIdAutoField'

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# --- PRODUCTION SECURITY SETTINGS ---

# Use environment variable for Secret Key; fallback only for local dev
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'django-insecure-e^%c%h64(&zl8syl3#^3f#a)f+&547uda#kexn6f)rveakh834')

# Set DEBUG to False for deployment (Safety first!)
DEBUG = False 

# Add your specific Render URL and local addresses
ALLOWED_HOSTS = ['ai-recommender-ecommerce.onrender.com', 'localhost', '127.0.0.1']

# --- APPLICATION DEFINITION ---

INSTALLED_APPS = [
    # Replaced default apps with Mongo-compatible versions
    'ecommerce_project.settings.MongoAdminConfig',
    'ecommerce_project.settings.MongoAuthConfig',
    'ecommerce_project.settings.MongoContentTypesConfig',
    
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'store',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware', # Essential for serving CSS on Render
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ecommerce_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ecommerce_project.wsgi.application'

# --- DATABASE CONFIGURATION ---

# Pulls the connection string from Render environment variables
# If no environment variable is found, it falls back to your local Atlas link
MONGO_URI = os.getenv('MONGO_URI', 'mongodb+srv://storeadmin:admin12345@cluster0.5yda63g.mongodb.net/')

DATABASES = {
    'default': {
        'ENGINE': 'django_mongodb_backend',
        'NAME': 'ecommerce_db',
        'HOST': MONGO_URI,
    }
}

# --- AI & EXTERNAL KEYS ---

# Placeholder for your future AI features
OPENAI_KEY = os.getenv("OPENAI_KEY")

# --- STANDARD DJANGO SETTINGS ---

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# --- STATIC FILES CONFIGURATION ---

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles') # For collectstatic
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django_mongodb_backend.fields.ObjectIdAutoField'